permissions_by_path.settings:
  type: mapping
  label: 'Permissions by Path settings'
  mapping:
    module_enable:
      type: boolean
      label: 'Enabled'
    affected_roles:
      type: sequence
      label: 'Roles affected'
      sequence:
        type: string
    affected_node_forms:
      type: sequence
      label: 'Content types affected'
      sequence:
        type: string
    path_permissions:
      type: sequence
      label: 'Path-to-users mappings'
      sequence:
        type: mapping
        mapping:
          path:
            type: string
            label: 'Path'
          users:
            type: sequence
            sequence:
              type: string
            label: 'Usernames'
